[package]
name = "mycelium"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.10.0", features = ["v7"] }
axum = { version = "0.7.5", features = ["json"] }
tokio = { version = "1.38.1", features = ["full"] }
serde = { version = "1.0.204", features = ["derive"] }
sqlx = { version = "0.7", features = [ "runtime-tokio", "postgres", "macros" ] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
serde_json = "1.0.120"
