name: mycelium_c2

services:
  mycelium-api:
    build:
      context: ./mycelium/
      target: runner
    ports:
      - 3000:3000
    links:
      - surrealdb
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:3000/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - mycelium-net
    depends_on:
      - surrealdb

  surrealdb:
    networks:
      - mycelium-net
    entrypoint:
      - /surreal
      - start
      - --log
      - trace
      - --allow-all
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
    image: surrealdb/surrealdb:v2.0.0-alpha.7
    ports:
      - 8000:8000
    environment:
      - .env

networks:
  mycelium-net:
volumes:
  db-data:
