
[tracing]
env_filter = "mycelium-api=trace,mycelium=trace,tower_http=debug"

[database]
host = "localhost"
username = "postgres"
password = "your database password"
db_name = "mycelium"

[http.listener]
addr = "0.0.0.0"
port = 3000

[http.routes.unauthenticated]
login = "/login"
ping = "/healthcheck"
healthcheck = "/healthcheck"

[http.routes.operators]
lookup_operator = "/operator/:id"
all_operators = "/operator/all"
new_operator = "/operator"
who_am_i = "/operator"
lookup_agent = "/agent/:id"
all_agents = "/agent/all"

[http.routes.implant]
beacon = "/beacon"

[tokens]
key_path = "ec-private.pem" # Useless so far - Not used to generate keys
ttl = "01d 00h 00m 00s"

