
[tracing]
env_filter = "mycelium-api=trace,mycelium=trace,tower_http=debug"

[database]
host = "localhost"#"postgres
username = "pguser"
password = "pgpassword"#"Mycelium_is_a_root_like_structure"
db_name = "mycelium"

[http.listener]
addr = "0.0.0.0"
port = 3000

[http.routes.unauthenticated]
login = "/login"
ping = "/healthcheck"
healthcheck = "/healthcheck"

[http.routes.operators]
lookup_operator = "/operator/:id"
all_operators = "/operator/all"
del_operator = "/operator/:id"
new_operator = "/operator"
who_am_i = "/operator"
lookup_agent = "/agent/:id"
all_agents = "/agent/all"

[http.routes.agent]
beacon = "/beacon"
upload = "/upload/:filename"

[tokens]
#key_path = "ec-private.pem" # Useless so far - Not used to generate keys but will be later
ttl = "01d 00h 00m 00s"

[misc]
uploads_dir = "./loot/"
