
[tracing]
env_filter = "mycelium-api=trace,mycelium=trace,tower_http=debug"

[database]
username = "root"
password = "Undiluted-Skinning-Elevate7"
connection = "ws://localhost:8000" # https://docs.rs/surrealdb/1.5.4/surrealdb/engine/any/fn.connect.html
database = "mycelium_db"
namespace = "mycelium_ns"

[http.listener]
address = "0.0.0.0"
port = 3000

[tokens]
ttl = "01d 00h 00m 00s"
iss = "Mycelium API"

[misc]
uploads_dir = "./loot/"
